# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalletMarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_origem', models.CharField(max_length=255, verbose_name='Pallet Origem')),
            ],
        ),
        migrations.CreateModel(
            name='PalletOrigem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Classe')),
                ('quatidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Quantidade')),
                ('metragem', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Metragem')),
                ('peso', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Peso')),
                ('lote', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Lote')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.PalletMarca')),
            ],
            options={
                'verbose_name': 'Pallet Origem',
                'verbose_name_plural': 'Pallet Origem',
            },
        ),
        migrations.CreateModel(
            name='PelePele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Pallet')),
                ('metragem', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Metragem')),
                ('quantidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Quantidade')),
                ('classe', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Classe')),
                ('peso', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Peso')),
                ('lote', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Pele a Pele',
                'verbose_name_plural': 'Peles a Peles',
            },
        ),
        migrations.CreateModel(
            name='Romaneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cliente')),
                ('quantidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Quantidade')),
                ('classe', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Classe')),
                ('metragem', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Metragem')),
                ('peso_liq', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Peso Liquido')),
                ('peso_bruto', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Peso Bruto')),
                ('data_saida', models.DateField()),
            ],
            options={
                'verbose_name': 'Romaneo',
                'verbose_name_plural': 'Romaneos',
            },
        ),
    ]
