# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('razao_social', models.CharField(blank=True, default=None, max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='CNPJ')),
                ('uf', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, default=None, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatidade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Quantidade')),
                ('classe', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Classe')),
                ('artigo', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Artigo')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Metragem')),
                ('espessura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Espessura')),
                ('cor', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Cor')),
                ('dataentrega', models.DateField(default=datetime.date.today, null=True, verbose_name='Data Entrega')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Data Entrega')),
                ('obs', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Observações')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.PedidoCliente')),
            ],
            options={
                'verbose_name': 'Pedido Descrição',
                'verbose_name_plural': 'Pedidos Descrições',
            },
        ),
        migrations.CreateModel(
            name='PedidoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, default=None, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('uf', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF')),
                ('transportadora', models.CharField(blank=True, max_length=255, verbose_name='Transportadora')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.PedidoCliente')),
            ],
        ),
    ]
