# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20180507_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoentrega',
            old_name='entrega',
            new_name='cliente',
        ),
    ]
