# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20180507_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoCliente',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='PedidoEntrega',
            new_name='Entrega',
        ),
        migrations.RenameModel(
            old_name='PedidoDescricao',
            new_name='Pedido',
        ),
    ]
