# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20180507_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.AutoField(default='0000', primary_key=True, serialize=False),
        ),
    ]
