# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20180507_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
