# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_auto_20180507_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pedido',
        ),
        migrations.AddField(
            model_name='entrega',
            name='cliente',
            field=models.ForeignKey(default=101010, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=0.1, on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
            preserve_default=False,
        ),
    ]
