# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_auto_20180507_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='cliente',
            new_name='pedido',
        ),
    ]
