# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20180507_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
        ),
    ]
