# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_auto_20180507_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
    ]
