# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_auto_20180508_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='dataentrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='transportadora',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
