# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0022_auto_20180508_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(default=None, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dataentrega',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Data Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='obs',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
        ),
    ]
