# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0023_auto_20180508_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrPedido',
            fields=[
                ('codigo', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Codigo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, default=0.000999000999000999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
