# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0025_auto_20180508_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataentrega', models.DateField(default=datetime.date.today, null=True, verbose_name='Data Entrega')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('obs', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Observações')),
                ('endereco', models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(default=None, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('uf', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF')),
                ('transportadora', models.CharField(blank=True, max_length=255, verbose_name='Transportadora')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='dataentrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='transportadora',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
