# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0026_auto_20180508_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='pedido',
            field=models.ForeignKey(default=0.08333333333333333, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido'),
            preserve_default=False,
        ),
    ]
