# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0028_auto_20180510_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='bairro',
            field=models.CharField(default=None, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='choice',
            name='cep',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='choice',
            name='cidade',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='choice',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='choice',
            name='endereco',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='choice',
            name='obs',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='choice',
            name='transportadora',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='choice',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='choice',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
        ),
    ]
