# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0031_auto_20180510_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
