# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0032_auto_20180510_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='valor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
        ),
    ]
