# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0034_auto_20180510_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='quatidade',
            new_name='quantidade',
        ),
    ]
