# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0035_auto_20180510_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
    ]
