# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0036_auto_20180511_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='entrega',
            name='codigo',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, default=0.09090909090909091, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
