# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0037_auto_20180511_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, default=None, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='uf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=20, null=True, verbose_name='E-MAIL'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='FONE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='NOME'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='RAZÃO SOCIAL'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
        ),
    ]
