# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0038_auto_20180511_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.ClientePedido'),
        ),
    ]
