# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0040_auto_20180511_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='entrega',
        ),
        migrations.AddField(
            model_name='clientepedido',
            name='entrega',
            field=models.ForeignKey(default=0.09090909090909091, on_delete=django.db.models.deletion.CASCADE, to='pedido.Entrega'),
            preserve_default=False,
        ),
    ]
